In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
from datetime import date, timedelta

In [2]:
result_list = []
for num in range(91, 544):
    url = 'https://finance.naver.com/marketindex/interestDailyQuote.nhn?marketindexCd=IRR_CALL'
    params = {
        'page' : num
    }
    resp = requests.get(url, params = params)
    soup = BeautifulSoup(resp.content, 'lxml')
    tr_list = soup.find_all('tr')[1:]
    for tr in tr_list:
        time = tr.find_all('td')[0].text.strip()
        a = time.split('.')
        time2 = date(int(a[0]), int(a[1]), int(a[2]))
        price = tr.find_all('td')[1].text
        
        new_dict = {
            'date' : time2,
            'callrate' : price
        }
        result_list.append(new_dict)

In [3]:
df = pd.DataFrame(result_list)
df = df.sort_values(by = 'date')
df

            date callrate
3170  2005-03-31     3.26
3169  2005-04-01     3.25
3168  2005-04-04     3.24
3167  2005-04-06     3.23
3166  2005-04-07     3.23
...          ...      ...
4     2017-12-26     1.52
3     2017-12-27     1.51
2     2017-12-28     1.55
1     2017-12-29     1.58
0     2018-01-02     1.52

[3171 rows x 2 columns]

In [4]:
df.drop(df.index[0], inplace = True)

In [5]:
df.drop(df.index[3169], inplace = True)

In [6]:
df

            date callrate
3169  2005-04-01     3.25
3168  2005-04-04     3.24
3167  2005-04-06     3.23
3166  2005-04-07     3.23
3165  2005-04-08     3.26
...          ...      ...
5     2017-12-22     1.51
4     2017-12-26     1.52
3     2017-12-27     1.51
2     2017-12-28     1.55
1     2017-12-29     1.58

[3169 rows x 2 columns]

In [7]:
date_df = pd.DataFrame(columns = ['date', 'callrate'])
start = date(2005, 4, 1)
end = date(2017, 12, 29)
for n in range(int((end - start).days) + 1):
    date_df.loc[n, 'date'] = start + timedelta(n)

In [8]:
date_df

            date callrate
0     2005-04-01      NaN
1     2005-04-02      NaN
2     2005-04-03      NaN
3     2005-04-04      NaN
4     2005-04-05      NaN
...          ...      ...
4651  2017-12-25      NaN
4652  2017-12-26      NaN
4653  2017-12-27      NaN
4654  2017-12-28      NaN
4655  2017-12-29      NaN

[4656 rows x 2 columns]

In [9]:
new_df = pd.merge(date_df, df, on = 'date', how = 'left')
new_df

            date callrate_x callrate_y
0     2005-04-01        NaN       3.25
1     2005-04-02        NaN        NaN
2     2005-04-03        NaN        NaN
3     2005-04-04        NaN       3.24
4     2005-04-05        NaN        NaN
...          ...        ...        ...
4651  2017-12-25        NaN        NaN
4652  2017-12-26        NaN       1.52
4653  2017-12-27        NaN       1.51
4654  2017-12-28        NaN       1.55
4655  2017-12-29        NaN       1.58

[4656 rows x 3 columns]

In [10]:
new_df.drop('callrate_x', axis = 'columns', inplace = True)

In [11]:
# new_df = new_df.set_index('date')
new_df

            date callrate_y
0     2005-04-01       3.25
1     2005-04-02        NaN
2     2005-04-03        NaN
3     2005-04-04       3.24
4     2005-04-05        NaN
...          ...        ...
4651  2017-12-25        NaN
4652  2017-12-26       1.52
4653  2017-12-27       1.51
4654  2017-12-28       1.55
4655  2017-12-29       1.58

[4656 rows x 2 columns]

In [12]:
new_df.fillna(method = 'pad', inplace=True)
new_df

            date callrate_y
0     2005-04-01       3.25
1     2005-04-02       3.25
2     2005-04-03       3.25
3     2005-04-04       3.24
4     2005-04-05       3.24
...          ...        ...
4651  2017-12-25       1.51
4652  2017-12-26       1.52
4653  2017-12-27       1.51
4654  2017-12-28       1.55
4655  2017-12-29       1.58

[4656 rows x 2 columns]

In [13]:
second_df  = pd.DataFrame(new_df)
second_df.head(50)

          date callrate_y
0   2005-04-01       3.25
1   2005-04-02       3.25
2   2005-04-03       3.25
3   2005-04-04       3.24
4   2005-04-05       3.24
5   2005-04-06       3.23
6   2005-04-07       3.23
7   2005-04-08       3.26
8   2005-04-09       3.26
9   2005-04-10       3.26
10  2005-04-11       3.25
11  2005-04-12       3.24
12  2005-04-13       3.25
13  2005-04-14       3.25
14  2005-04-15       3.26
15  2005-04-16       3.26
16  2005-04-17       3.26
17  2005-04-18       3.25
18  2005-04-19       3.26
19  2005-04-20       3.26
20  2005-04-21       3.23
21  2005-04-22       3.24
22  2005-04-23       3.24
23  2005-04-24       3.24
24  2005-04-25       3.26
25  2005-04-26       3.26
26  2005-04-27       3.27
27  2005-04-28       3.27
28  2005-04-29       3.29
29  2005-04-30       3.29
30  2005-05-01       3.29
31  2005-05-02       3.29
32  2005-05-03       3.30
33  2005-05-04       3.21
34  2005-05-05       3.21
35  2005-05-06       3.27
36  2005-05-07       3.27
37  2005-05-08       3.27
38  2005-05-09       3.29
39  2005-05-10       3.30
40  2005-05-11       3.30
41  2005-05-12       3.30
42  2005-05-13       3.29
43  2005-05-14       3.29
44  2005-05-15       3.29
45  2005-05-16       3.29
46  2005-05-17       3.29
47  2005-05-18       3.29
48  2005-05-19       3.19
49  2005-05-20       3.23

In [14]:
second_df.drop(second_df.index[0:30], inplace = True)

In [15]:
second_df.reset_index(drop = True, inplace = True)

In [16]:
second_df

            date callrate_y
0     2005-05-01       3.29
1     2005-05-02       3.29
2     2005-05-03       3.30
3     2005-05-04       3.21
4     2005-05-05       3.21
...          ...        ...
4621  2017-12-25       1.51
4622  2017-12-26       1.52
4623  2017-12-27       1.51
4624  2017-12-28       1.55
4625  2017-12-29       1.58

[4626 rows x 2 columns]

In [17]:
second_df['한달전 date'] = second_df['date'] - pd.DateOffset(30)

In [18]:
second_df

            date callrate_y   한달전 date
0     2005-05-01       3.29 2005-04-01
1     2005-05-02       3.29 2005-04-02
2     2005-05-03       3.30 2005-04-03
3     2005-05-04       3.21 2005-04-04
4     2005-05-05       3.21 2005-04-05
...          ...        ...        ...
4621  2017-12-25       1.51 2017-11-25
4622  2017-12-26       1.52 2017-11-26
4623  2017-12-27       1.51 2017-11-27
4624  2017-12-28       1.55 2017-11-28
4625  2017-12-29       1.58 2017-11-29

[4626 rows x 3 columns]

In [19]:
second_df['한달전 callrate'] = new_df['callrate_y'][0:4626]

In [20]:
second_df = second_df.rename(columns = {'callrate_y':'callrate'})

In [21]:
final_df = pd.DataFrame(second_df)
final_df['labeling'] = np.zeros(len(final_df))

In [22]:
tmp = []
for i in final_df.iloc:
    if i['callrate'] > i['한달전 callrate']:
        tmp.append('up')
    elif i['callrate'] == i['한달전 callrate']:
        tmp.append(0)
    else:
        tmp.append('down')
final_df.labeling = tmp

In [27]:
final_df

            date callrate   한달전 date 한달전 callrate labeling
0     2005-05-01     3.29 2005-04-01         3.25       up
1     2005-05-02     3.29 2005-04-02         3.25       up
2     2005-05-03     3.30 2005-04-03         3.25       up
3     2005-05-04     3.21 2005-04-04         3.24     down
4     2005-05-05     3.21 2005-04-05         3.24     down
...          ...      ...        ...          ...      ...
4621  2017-12-25     1.51 2017-11-25         1.25       up
4622  2017-12-26     1.52 2017-11-26         1.25       up
4623  2017-12-27     1.51 2017-11-27         1.26       up
4624  2017-12-28     1.55 2017-11-28         1.26       up
4625  2017-12-29     1.58 2017-11-29         1.26       up

[4626 rows x 5 columns]

In [30]:
final_df.to_csv('callrate.csv', encoding = 'utf-8-sig', header = ['date','callrate', '한달전 date', '한달전 callrate', 'labeling'], index = False)

In [147]:
# tmp = 0

# for i in new_df['date']:
#     if i in df.index:
#         i = str(i)
#         year = i[0:4]
#         month = i[5:7]
#         if month[0] == '0':
#             month = month.replace('0', '')
#         day = i[8:10]
#         if day[0] == '0':
#             day = day.replace('0', '')

2005 4 1
2005 4 4
2005 4 6
2005 4 7
2005 4 8
2005 4 11
2005 4 12
2005 4 13
2005 4 14
2005 4 15
2005 4 18
2005 4 19
2005 4 20
2005 4 21
2005 4 22
2005 4 25
2005 4 26
2005 4 27
2005 4 28
2005 4 29
2005 5 2
2005 5 3
2005 5 4
2005 5 6
2005 5 9
2005 5 10
2005 5 11
2005 5 12
2005 5 13
2005 5 16
2005 5 17
2005 5 18
2005 5 19
2005 5 20
2005 5 23
2005 5 24
2005 5 25
2005 5 26
2005 5 27
2005 5 30
2005 5 31
2005 6 1
2005 6 2
2005 6 3
2005 6 7
2005 6 8
2005 6 9
2005 6 10
2005 6 13
2005 6 14
2005 6 15
2005 6 16
2005 6 17
2005 6 20
2005 6 21
2005 6 22
2005 6 23
2005 6 24
2005 6 27
2005 6 28
2005 6 29
2005 6 30
2005 7 1
2005 7 4
2005 7 5
2005 7 6
2005 7 7
2005 7 8
2005 7 11
2005 7 12
2005 7 13
2005 7 14
2005 7 15
2005 7 18
2005 7 19
2005 7 20
2005 7 21
2005 7 22
2005 7 25
2005 7 26
2005 7 27
2005 7 28
2005 7 29
2005 8 1
2005 8 2
2005 8 3
2005 8 4
2005 8 5
2005 8 8
2005 8 9
2005 8 10
2005 8 11
2005 8 12
2005 8 16
2005 8 17
2005 8 18
2005 8 19
2005 8 22
2005 8 23
2005 8 24
2005 8 25
2005 8 26
2005 8 29
2005 8 30
2005 8 31
2005 9 1
2005 9 2
2005 9 5
2005 9 6
2005 9 7
2005 9 8
2005 9 9
2005 9 12
2005 9 13
2005 9 14
2005 9 15
2005 9 16
2005 9 20
2005 9 21
2005 9 22
2005 9 23
2005 9 26
2005 9 27
2005 9 28
2005 9 29
2005 9 30
2005 10 4
2005 10 5
2005 10 6
2005 10 7
2005 10 10
2005 10 11
2005 10 12
2005 10 13
2005 10 14
2005 10 17
2005 10 18
2005 10 19
2005 10 20
2005 10 21
2005 10 24
2005 10 25
2005 10 26
2005 10 27
2005 10 28
2005 10 31
2005 11 1
2005 11 2
2005 11 3
2005 11 4
2005 11 7
2005 11 8
2005 11 9
2005 11 10
2005 11 11
2005 11 14
2005 11 15
2005 11 16
2005 11 17
2005 11 18
2005 11 21
2005 11 22
2005 11 23
2005 11 24
2005 11 25
2005 11 28
2005 11 29
2005 11 30
2005 12 1
2005 12 2
2005 12 5
2005 12 6
2005 12 7
2005 12 8
2005 12 9
2005 12 12
2005 12 13
2005 12 14
2005 12 15
2005 12 16
2005 12 19
2005 12 20
2005 12 21
2005 12 22
2005 12 23
2005 12 26
2005 12 27
2005 12 28
2005 12 29
2005 12 30
2006 1 2
2006 1 3
2006 1 4
2006 1 5
2006 1 6
2006 1 9
2006 1 10
2006 1 11
2006 1 12
2006 1 13
2006 1 16
2006 1 17
2006 1 18
2006 1 19
2006 1 20
2006 1 23
2006 1 24
2006 1 25
2006 1 26
2006 1 27
2006 1 31
2006 2 1
2006 2 2
2006 2 3
2006 2 6
2006 2 7
2006 2 8
2006 2 9
2006 2 10
2006 2 13
2006 2 14
2006 2 15
2006 2 16
2006 2 17
2006 2 20
2006 2 21
2006 2 22
2006 2 23
2006 2 24
2006 2 27
2006 2 28
2006 3 2
2006 3 3
2006 3 6
2006 3 7
2006 3 8
2006 3 9
2006 3 10
2006 3 13
2006 3 14
2006 3 15
2006 3 16
2006 3 17
2006 3 20
2006 3 21
2006 3 22
2006 3 23
2006 3 24
2006 3 27
2006 3 28
2006 3 29
2006 3 30
2006 3 31
2006 4 3
2006 4 4
2006 4 5
2006 4 6
2006 4 7
2006 4 10
2006 4 11
2006 4 12
2006 4 13
2006 4 14
2006 4 17
2006 4 18
2006 4 19
2006 4 20
2006 4 21
2006 4 24
2006 4 25
2006 4 26
2006 4 27
2006 4 28
2006 5 2
2006 5 3
2006 5 4
2006 5 8
2006 5 9
2006 5 10
2006 5 11
2006 5 12
2006 5 15
2006 5 16
2006 5 17
2006 5 18
2006 5 19
2006 5 22
2006 5 23
2006 5 24
2006 5 25
2006 5 26
2006 5 29
2006 5 30
2006 6 1
2006 6 2
2006 6 5
2006 6 7
2006 6 8
2006 6 9
2006 6 12
2006 6 13
2006 6 14
2006 6 15
2006 6 16
2006 6 19
2006 6 20
2006 6 21
2006 6 22
2006 6 23
2006 6 26
2006 6 27
2006 6 28
2006 6 29
2006 6 30
2006 7 3
2006 7 4
2006 7 5
2006 7 6
2006 7 7
2006 7 10
2006 7 11
2006 7 12
2006 7 13
2006 7 14
2006 7 18
2006 7 19
2006 7 20
2006 7 21
2006 7 24
2006 7 25
2006 7 26
2006 7 27
2006 7 28
2006 7 31
2006 8 1
2006 8 2
2006 8 3
2006 8 4
2006 8 7
2006 8 8
2006 8 9
2006 8 10
2006 8 11
2006 8 14
2006 8 16
2006 8 17
2006 8 18
2006 8 21
2006 8 22
2006 8 23
2006 8 24
2006 8 25
2006 8 28
2006 8 29
2006 8 30
2006 8 31
2006 9 1
2006 9 4
2006 9 5
2006 9 6
2006 9 7
2006 9 8
2006 9 11
2006 9 12
2006 9 13
2006 9 14
2006 9 15
2006 9 18
2006 9 19
2006 9 20
2006 9 21
2006 9 22
2006 9 25
2006 9 26
2006 9 27
2006 9 28
2006 9 29
2006 10 2
2006 10 4
2006 10 9
2006 10 10
2006 10 11
2006 10 12
2006 10 13
2006 10 16
2006 10 17
2006 10 18
2006 10 19
2006 10 20
2006 10 23
2006 10 24
2006 10 25
2006 10 26
2006 10 27
2006 10 30
2006 10 31
2006 11 1
2006 11 2
2006 11 3
2006 11 6
2006 11 7
2006 11 8
2006 11 9
2006 11 10
2006 11 13
2006 11 14
2006 11 15
2006 11 16
2006 11 17
2006 11 20
2006 11 21
2006 11 22
2006 11 23
2006 11 24
2006 11 27
2006 11 28
2006 11 29
2006 11 30
2006 12 1
2006 12 4
2006 12 5
2006 12 6
2006 12 7
2006 12 8
2006 12 11
2006 12 12
2006 12 13
2006 12 14
2006 12 15
2006 12 18
2006 12 19
2006 12 20
2006 12 21
2006 12 22
2006 12 26
2006 12 27
2006 12 28
2006 12 29
2007 1 2
2007 1 3
2007 1 4
2007 1 5
2007 1 8
2007 1 9
2007 1 10
2007 1 11
2007 1 12
2007 1 15
2007 1 16
2007 1 17
2007 1 18
2007 1 19
2007 1 22
2007 1 23
2007 1 24
2007 1 25
2007 1 26
2007 1 29
2007 1 30
2007 1 31
2007 2 1
2007 2 2
2007 2 5
2007 2 6
2007 2 7
2007 2 8
2007 2 9
2007 2 12
2007 2 13
2007 2 14
2007 2 15
2007 2 16
2007 2 20
2007 2 21
2007 2 22
2007 2 23
2007 2 26
2007 2 27
2007 2 28
2007 3 2
2007 3 5
2007 3 6
2007 3 7
2007 3 8
2007 3 9
2007 3 12
2007 3 13
2007 3 14
2007 3 15
2007 3 16
2007 3 19
2007 3 20
2007 3 21
2007 3 22
2007 3 23
2007 3 26
2007 3 27
2007 3 28
2007 3 29
2007 3 30
2007 4 2
2007 4 3
2007 4 4
2007 4 5
2007 4 6
2007 4 9
2007 4 10
2007 4 11
2007 4 12
2007 4 13
2007 4 16
2007 4 17
2007 4 18
2007 4 19
2007 4 20
2007 4 23
2007 4 24
2007 4 25
2007 4 26
2007 4 27
2007 4 30
2007 5 2
2007 5 3
2007 5 4
2007 5 7
2007 5 8
2007 5 9
2007 5 10
2007 5 11
2007 5 14
2007 5 15
2007 5 16
2007 5 17
2007 5 18
2007 5 21
2007 5 22
2007 5 23
2007 5 25
2007 5 28
2007 5 29
2007 5 30
2007 5 31
2007 6 1
2007 6 4
2007 6 5
2007 6 7
2007 6 8
2007 6 11
2007 6 12
2007 6 13
2007 6 14
2007 6 15
2007 6 18
2007 6 19
2007 6 20
2007 6 21
2007 6 22
2007 6 25
2007 6 26
2007 6 27
2007 6 28
2007 6 29
2007 7 2
2007 7 3
2007 7 4
2007 7 5
2007 7 6
2007 7 9
2007 7 10
2007 7 11
2007 7 12
2007 7 13
2007 7 16
2007 7 18
2007 7 19
2007 7 20
2007 7 23
2007 7 24
2007 7 25
2007 7 26
2007 7 27
2007 7 30
2007 7 31
2007 8 1
2007 8 2
2007 8 3
2007 8 6
2007 8 7
2007 8 8
2007 8 9
2007 8 10
2007 8 13
2007 8 14
2007 8 16
2007 8 17
2007 8 20
2007 8 21
2007 8 22
2007 8 23
2007 8 24
2007 8 27
2007 8 28
2007 8 29
2007 8 30
2007 8 31
2007 9 3
2007 9 4
2007 9 5
2007 9 6
2007 9 7
2007 9 10
2007 9 11
2007 9 12
2007 9 13
2007 9 14
2007 9 17
2007 9 18
2007 9 19
2007 9 20
2007 9 21
2007 9 27
2007 9 28
2007 10 1
2007 10 2
2007 10 4
2007 10 5
2007 10 8
2007 10 9
2007 10 10
2007 10 11
2007 10 12
2007 10 15
2007 10 16
2007 10 17
2007 10 18
2007 10 19
2007 10 22
2007 10 23
2007 10 24
2007 10 25
2007 10 26
2007 10 29
2007 10 30
2007 10 31
2007 11 1
2007 11 2
2007 11 5
2007 11 6
2007 11 7
2007 11 8
2007 11 9
2007 11 12
2007 11 13
2007 11 14
2007 11 15
2007 11 16
2007 11 19
2007 11 20
2007 11 21
2007 11 22
2007 11 23
2007 11 26
2007 11 27
2007 11 28
2007 11 29
2007 11 30
2007 12 3
2007 12 4
2007 12 5
2007 12 6
2007 12 7
2007 12 10
2007 12 11
2007 12 12
2007 12 13
2007 12 14
2007 12 17
2007 12 18
2007 12 20
2007 12 21
2007 12 24
2007 12 26
2007 12 27
2007 12 31
2008 1 2
2008 1 3
2008 1 4
2008 1 7
2008 1 8
2008 1 9
2008 1 10
2008 1 11
2008 1 14
2008 1 15
2008 1 16
2008 1 17
2008 1 18
2008 1 21
2008 1 22
2008 1 23
2008 1 24
2008 1 25
2008 1 28
2008 1 29
2008 1 30
2008 1 31
2008 2 1
2008 2 4
2008 2 5
2008 2 11
2008 2 12
2008 2 13
2008 2 14
2008 2 15
2008 2 18
2008 2 19
2008 2 20
2008 2 21
2008 2 22
2008 2 25
2008 2 26
2008 2 27
2008 2 28
2008 2 29
2008 3 3
2008 3 4
2008 3 5
2008 3 6
2008 3 7
2008 3 10
2008 3 11
2008 3 12
2008 3 13
2008 3 14
2008 3 17
2008 3 18
2008 3 19
2008 3 20
2008 3 21
2008 3 24
2008 3 25
2008 3 26
2008 3 27
2008 3 28
2008 3 31
2008 4 1
2008 4 2
2008 4 3
2008 4 4
2008 4 7
2008 4 8
2008 4 10
2008 4 11
2008 4 14
2008 4 15
2008 4 16
2008 4 17
2008 4 18
2008 4 21
2008 4 22
2008 4 23
2008 4 24
2008 4 25
2008 4 28
2008 4 29
2008 4 30
2008 5 2
2008 5 6
2008 5 7
2008 5 8
2008 5 9
2008 5 13
2008 5 14
2008 5 15
2008 5 16
2008 5 19
2008 5 20
2008 5 21
2008 5 22
2008 5 23
2008 5 26
2008 5 27
2008 5 28
2008 5 29
2008 5 30
2008 6 2
2008 6 3
2008 6 4
2008 6 5
2008 6 9
2008 6 10
2008 6 11
2008 6 12
2008 6 13
2008 6 16
2008 6 17
2008 6 18
2008 6 19
2008 6 20
2008 6 23
2008 6 24
2008 6 25
2008 6 26
2008 6 27
2008 6 30
2008 7 1
2008 7 2
2008 7 3
2008 7 4
2008 7 7
2008 7 8
2008 7 9
2008 7 10
2008 7 11
2008 7 14
2008 7 15
2008 7 16
2008 7 17
2008 7 18
2008 7 21
2008 7 22
2008 7 23
2008 7 24
2008 7 25
2008 7 28
2008 7 29
2008 7 30
2008 7 31
2008 8 1
2008 8 4
2008 8 5
2008 8 6
2008 8 7
2008 8 8
2008 8 11
2008 8 12
2008 8 13
2008 8 14
2008 8 18
2008 8 19
2008 8 20
2008 8 21
2008 8 22
2008 8 25
2008 8 26
2008 8 27
2008 8 28
2008 8 29
2008 9 1
2008 9 2
2008 9 3
2008 9 4
2008 9 5
2008 9 8
2008 9 9
2008 9 10
2008 9 11
2008 9 12
2008 9 16
2008 9 17
2008 9 18
2008 9 19
2008 9 22
2008 9 23
2008 9 24
2008 9 25
2008 9 26
2008 9 29
2008 9 30
2008 10 1
2008 10 2
2008 10 6
2008 10 7
2008 10 8
2008 10 9
2008 10 10
2008 10 13
2008 10 14
2008 10 15
2008 10 16
2008 10 17
2008 10 20
2008 10 21
2008 10 22
2008 10 23
2008 10 24
2008 10 27
2008 10 28
2008 10 29
2008 10 30
2008 10 31
2008 11 3
2008 11 4
2008 11 5
2008 11 6
2008 11 7
2008 11 10
2008 11 11
2008 11 12
2008 11 13
2008 11 14
2008 11 17
2008 11 18
2008 11 19
2008 11 20
2008 11 21
2008 11 24
2008 11 25
2008 11 26
2008 11 27
2008 11 28
2008 12 1
2008 12 2
2008 12 3
2008 12 4
2008 12 5
2008 12 8
2008 12 9
2008 12 10
2008 12 11
2008 12 12
2008 12 15
2008 12 16
2008 12 17
2008 12 18
2008 12 19
2008 12 22
2008 12 23
2008 12 24
2008 12 26
2008 12 29
2008 12 30
2008 12 31
2009 1 2
2009 1 5
2009 1 6
2009 1 7
2009 1 8
2009 1 9
2009 1 12
2009 1 13
2009 1 14
2009 1 15
2009 1 16
2009 1 19
2009 1 20
2009 1 21
2009 1 22
2009 1 23
2009 1 28
2009 1 29
2009 1 30
2009 2 2
2009 2 3
2009 2 4
2009 2 5
2009 2 6
2009 2 9
2009 2 10
2009 2 11
2009 2 12
2009 2 13
2009 2 16
2009 2 17
2009 2 18
2009 2 19
2009 2 20
2009 2 23
2009 2 24
2009 2 25
2009 2 26
2009 2 27
2009 3 2
2009 3 3
2009 3 4
2009 3 5
2009 3 6
2009 3 9
2009 3 10
2009 3 11
2009 3 12
2009 3 13
2009 3 16
2009 3 17
2009 3 18
2009 3 19
2009 3 20
2009 3 23
2009 3 24
2009 3 25
2009 3 26
2009 3 27
2009 3 30
2009 3 31
2009 4 1
2009 4 2
2009 4 3
2009 4 6
2009 4 7
2009 4 8
2009 4 9
2009 4 10
2009 4 13
2009 4 14
2009 4 15
2009 4 16
2009 4 17
2009 4 20
2009 4 21
2009 4 22
2009 4 23
2009 4 24
2009 4 27
2009 4 28
2009 4 29
2009 4 30
2009 5 4
2009 5 6
2009 5 7
2009 5 8
2009 5 11
2009 5 12
2009 5 13
2009 5 14
2009 5 15
2009 5 18
2009 5 19
2009 5 20
2009 5 21
2009 5 22
2009 5 25
2009 5 26
2009 5 27
2009 5 28
2009 5 29
2009 6 1
2009 6 2
2009 6 3
2009 6 4
2009 6 5
2009 6 8
2009 6 9
2009 6 10
2009 6 11
2009 6 12
2009 6 15
2009 6 16
2009 6 17
2009 6 18
2009 6 19
2009 6 22
2009 6 23
2009 6 24
2009 6 25
2009 6 26
2009 6 29
2009 6 30
2009 7 1
2009 7 2
2009 7 3
2009 7 6
2009 7 7
2009 7 8
2009 7 9
2009 7 10
2009 7 13
2009 7 14
2009 7 15
2009 7 16
2009 7 17
2009 7 20
2009 7 21
2009 7 22
2009 7 23
2009 7 24
2009 7 27
2009 7 28
2009 7 29
2009 7 30
2009 7 31
2009 8 3
2009 8 4
2009 8 5
2009 8 6
2009 8 7
2009 8 10
2009 8 11
2009 8 12
2009 8 13
2009 8 14
2009 8 17
2009 8 18
2009 8 19
2009 8 20
2009 8 21
2009 8 24
2009 8 25
2009 8 26
2009 8 27
2009 8 28
2009 8 31
2009 9 1
2009 9 2
2009 9 3
2009 9 4
2009 9 7
2009 9 8
2009 9 9
2009 9 10
2009 9 11
2009 9 14
2009 9 15
2009 9 16
2009 9 17
2009 9 18
2009 9 21
2009 9 22
2009 9 23
2009 9 24
2009 9 25
2009 9 28
2009 9 29
2009 9 30
2009 10 1
2009 10 5
2009 10 6
2009 10 7
2009 10 8
2009 10 9
2009 10 12
2009 10 13
2009 10 14
2009 10 15
2009 10 16
2009 10 19
2009 10 20
2009 10 21
2009 10 22
2009 10 23
2009 10 26
2009 10 27
2009 10 28
2009 10 29
2009 10 30
2009 11 2
2009 11 3
2009 11 4
2009 11 5
2009 11 6
2009 11 9
2009 11 10
2009 11 11
2009 11 12
2009 11 13
2009 11 16
2009 11 17
2009 11 18
2009 11 19
2009 11 20
2009 11 23
2009 11 24
2009 11 25
2009 11 26
2009 11 27
2009 11 30
2009 12 1
2009 12 2
2009 12 3
2009 12 4
2009 12 7
2009 12 8
2009 12 9
2009 12 10
2009 12 11
2009 12 14
2009 12 15
2009 12 16
2009 12 17
2009 12 18
2009 12 21
2009 12 22
2009 12 23
2009 12 24
2009 12 28
2009 12 29
2009 12 30
2009 12 31
2010 1 4
2010 1 5
2010 1 6
2010 1 7
2010 1 8
2010 1 11
2010 1 12
2010 1 13
2010 1 14
2010 1 15
2010 1 18
2010 1 19
2010 1 20
2010 1 21
2010 1 22
2010 1 25
2010 1 26
2010 1 27
2010 1 28
2010 1 29
2010 2 1
2010 2 2
2010 2 3
2010 2 4
2010 2 5
2010 2 8
2010 2 9
2010 2 10
2010 2 11
2010 2 12
2010 2 16
2010 2 17
2010 2 18
2010 2 19
2010 2 22
2010 2 23
2010 2 24
2010 2 25
2010 2 26
2010 3 2
2010 3 3
2010 3 4
2010 3 5
2010 3 8
2010 3 9
2010 3 10
2010 3 11
2010 3 12
2010 3 15
2010 3 16
2010 3 17
2010 3 18
2010 3 19
2010 3 22
2010 3 23
2010 3 24
2010 3 25
2010 3 26
2010 3 29
2010 3 30
2010 3 31
2010 4 1
2010 4 2
2010 4 5
2010 4 6
2010 4 7
2010 4 8
2010 4 9
2010 4 12
2010 4 13
2010 4 14
2010 4 15
2010 4 16
2010 4 19
2010 4 20
2010 4 21
2010 4 22
2010 4 23
2010 4 26
2010 4 27
2010 4 28
2010 4 29
2010 4 30
2010 5 3
2010 5 4
2010 5 6
2010 5 7
2010 5 10
2010 5 11
2010 5 12
2010 5 13
2010 5 14
2010 5 17
2010 5 18
2010 5 19
2010 5 20
2010 5 24
2010 5 25
2010 5 26
2010 5 27
2010 5 28
2010 5 31
2010 6 1
2010 6 3
2010 6 4
2010 6 7
2010 6 8
2010 6 9
2010 6 10
2010 6 11
2010 6 14
2010 6 15
2010 6 16
2010 6 17
2010 6 18
2010 6 21
2010 6 22
2010 6 23
2010 6 24
2010 6 25
2010 6 28
2010 6 29
2010 6 30
2010 7 1
2010 7 2
2010 7 5
2010 7 6
2010 7 7
2010 7 8
2010 7 9
2010 7 12
2010 7 13
2010 7 14
2010 7 15
2010 7 16
2010 7 19
2010 7 20
2010 7 21
2010 7 22
2010 7 23
2010 7 26
2010 7 27
2010 7 28
2010 7 29
2010 7 30
2010 8 2
2010 8 3
2010 8 4
2010 8 5
2010 8 6
2010 8 9
2010 8 10
2010 8 11
2010 8 12
2010 8 13
2010 8 16
2010 8 17
2010 8 18
2010 8 19
2010 8 20
2010 8 23
2010 8 24
2010 8 25
2010 8 26
2010 8 27
2010 8 30
2010 8 31
2010 9 1
2010 9 2
2010 9 3
2010 9 6
2010 9 7
2010 9 8
2010 9 9
2010 9 10
2010 9 13
2010 9 14
2010 9 15
2010 9 16
2010 9 17
2010 9 20
2010 9 24
2010 9 27
2010 9 28
2010 9 29
2010 9 30
2010 10 1
2010 10 4
2010 10 5
2010 10 6
2010 10 7
2010 10 8
2010 10 11
2010 10 12
2010 10 13
2010 10 14
2010 10 15
2010 10 18
2010 10 19
2010 10 20
2010 10 21
2010 10 22
2010 10 25
2010 10 26
2010 10 27
2010 10 28
2010 10 29
2010 11 1
2010 11 2
2010 11 3
2010 11 4
2010 11 5
2010 11 8
2010 11 9
2010 11 10
2010 11 11
2010 11 12
2010 11 15
2010 11 16
2010 11 17
2010 11 18
2010 11 19
2010 11 22
2010 11 23
2010 11 24
2010 11 25
2010 11 26
2010 11 29
2010 11 30
2010 12 1
2010 12 2
2010 12 3
2010 12 6
2010 12 7
2010 12 8
2010 12 9
2010 12 10
2010 12 13
2010 12 14
2010 12 15
2010 12 16
2010 12 17
2010 12 20
2010 12 21
2010 12 22
2010 12 23
2010 12 24
2010 12 27
2010 12 28
2010 12 29
2010 12 30
2010 12 31
2011 1 3
2011 1 4
2011 1 5
2011 1 6
2011 1 7
2011 1 10
2011 1 11
2011 1 12
2011 1 13
2011 1 14
2011 1 17
2011 1 18
2011 1 19
2011 1 20
2011 1 21
2011 1 24
2011 1 25
2011 1 26
2011 1 27
2011 1 28
2011 1 31
2011 2 1
2011 2 7
2011 2 8
2011 2 9
2011 2 10
2011 2 11
2011 2 14
2011 2 15
2011 2 16
2011 2 17
2011 2 18
2011 2 21
2011 2 22
2011 2 23
2011 2 24
2011 2 25
2011 2 28
2011 3 2
2011 3 3
2011 3 4
2011 3 7
2011 3 8
2011 3 9
2011 3 10
2011 3 11
2011 3 14
2011 3 15
2011 3 16
2011 3 17
2011 3 18
2011 3 21
2011 3 22
2011 3 23

2011 3 24
2011 3 25
2011 3 28
2011 3 29
2011 3 30
2011 3 31
2011 4 1
2011 4 4
2011 4 5
2011 4 6
2011 4 7
2011 4 8
2011 4 11
2011 4 12
2011 4 13
2011 4 14
2011 4 15
2011 4 18
2011 4 19
2011 4 20
2011 4 21
2011 4 22
2011 4 25
2011 4 26
2011 4 27
2011 4 28
2011 4 29
2011 5 2
2011 5 3
2011 5 4
2011 5 6
2011 5 9
2011 5 11
2011 5 12
2011 5 13
2011 5 16
2011 5 17
2011 5 18
2011 5 19
2011 5 20
2011 5 23
2011 5 24
2011 5 25
2011 5 26
2011 5 27
2011 5 30
2011 5 31
2011 6 1
2011 6 2
2011 6 3
2011 6 7
2011 6 8
2011 6 9
2011 6 10
2011 6 13
2011 6 14
2011 6 15
2011 6 16
2011 6 17
2011 6 20
2011 6 21
2011 6 22
2011 6 23
2011 6 24
2011 6 27
2011 6 28
2011 6 29
2011 6 30
2011 7 1
2011 7 4
2011 7 5
2011 7 6
2011 7 7
2011 7 8
2011 7 11
2011 7 12
2011 7 13
2011 7 14
2011 7 15
2011 7 18
2011 7 19
2011 7 20
2011 7 21
2011 7 22
2011 7 25
2011 7 26
2011 7 27
2011 7 28
2011 7 29
2011 8 1
2011 8 2
2011 8 3
2011 8 4
2011 8 5
2011 8 8
2011 8 9
2011 8 10
2011 8 11
2011 8 12
2011 8 16
2011 8 17
2011 8 18
2011 8 19
2011 8 22
2011 8 23
2011 8 24
2011 8 25
2011 8 26
2011 8 29
2011 8 30
2011 8 31
2011 9 1
2011 9 2
2011 9 5
2011 9 6
2011 9 7
2011 9 8
2011 9 9
2011 9 14
2011 9 15
2011 9 16
2011 9 19
2011 9 20
2011 9 21
2011 9 22
2011 9 23
2011 9 26
2011 9 27
2011 9 28
2011 9 29
2011 9 30
2011 10 4
2011 10 5
2011 10 6
2011 10 7
2011 10 10
2011 10 11
2011 10 12
2011 10 13
2011 10 14
2011 10 17
2011 10 18
2011 10 19
2011 10 20
2011 10 21
2011 10 24
2011 10 25
2011 10 26
2011 10 27
2011 10 28
2011 10 31
2011 11 1
2011 11 2
2011 11 3
2011 11 4
2011 11 7
2011 11 8
2011 11 9
2011 11 10
2011 11 11
2011 11 14
2011 11 15
2011 11 16
2011 11 17
2011 11 18
2011 11 21
2011 11 22
2011 11 23
2011 11 24
2011 11 25
2011 11 28
2011 11 29
2011 11 30
2011 12 1
2011 12 2
2011 12 5
2011 12 6
2011 12 7
2011 12 8
2011 12 9
2011 12 12
2011 12 13
2011 12 14
2011 12 15
2011 12 16
2011 12 19
2011 12 20
2011 12 21
2011 12 22
2011 12 23
2011 12 26
2011 12 27
2011 12 28
2011 12 29
2011 12 30
2012 1 2
2012 1 3
2012 1 4
2012 1 5
2012 1 6
2012 1 9
2012 1 10
2012 1 11
2012 1 12
2012 1 13
2012 1 16
2012 1 17
2012 1 18
2012 1 19
2012 1 20
2012 1 25
2012 1 26
2012 1 27
2012 1 30
2012 1 31
2012 2 1
2012 2 2
2012 2 3
2012 2 6
2012 2 7
2012 2 8
2012 2 9
2012 2 10
2012 2 13
2012 2 14
2012 2 15
2012 2 16
2012 2 17
2012 2 20
2012 2 21
2012 2 22
2012 2 23
2012 2 24
2012 2 27
2012 2 28
2012 2 29
2012 3 2
2012 3 5
2012 3 6
2012 3 7
2012 3 8
2012 3 9
2012 3 12
2012 3 13
2012 3 14
2012 3 15
2012 3 16
2012 3 19
2012 3 20
2012 3 21
2012 3 22
2012 3 23
2012 3 26
2012 3 27
2012 3 28
2012 3 29
2012 3 30
2012 4 2
2012 4 3
2012 4 4
2012 4 5
2012 4 6
2012 4 9
2012 4 10
2012 4 12
2012 4 13
2012 4 16
2012 4 17
2012 4 18
2012 4 19
2012 4 20
2012 4 23
2012 4 24
2012 4 25
2012 4 26
2012 4 27
2012 4 30
2012 5 2
2012 5 3
2012 5 4
2012 5 7
2012 5 8
2012 5 9
2012 5 10
2012 5 11
2012 5 14
2012 5 15
2012 5 16
2012 5 17
2012 5 18
2012 5 21
2012 5 22
2012 5 23
2012 5 24
2012 5 25
2012 5 29
2012 5 30
2012 5 31
2012 6 1
2012 6 4
2012 6 5
2012 6 7
2012 6 8
2012 6 11
2012 6 12
2012 6 13
2012 6 14
2012 6 15
2012 6 18
2012 6 19
2012 6 20
2012 6 21
2012 6 22
2012 6 25
2012 6 26
2012 6 27
2012 6 28
2012 6 29
2012 7 2
2012 7 3
2012 7 4
2012 7 5
2012 7 6
2012 7 9
2012 7 10
2012 7 11
2012 7 12
2012 7 13
2012 7 16
2012 7 17
2012 7 18
2012 7 19
2012 7 20
2012 7 23
2012 7 24
2012 7 25
2012 7 26
2012 7 27
2012 7 30
2012 7 31
2012 8 1
2012 8 2
2012 8 3
2012 8 6
2012 8 7
2012 8 8
2012 8 9
2012 8 10
2012 8 13
2012 8 14
2012 8 16
2012 8 17
2012 8 20
2012 8 21
2012 8 22
2012 8 23
2012 8 24
2012 8 27
2012 8 28
2012 8 29
2012 8 30
2012 8 31
2012 9 3
2012 9 4
2012 9 5
2012 9 6
2012 9 7
2012 9 10
2012 9 11
2012 9 12
2012 9 13
2012 9 14
2012 9 17
2012 9 18
2012 9 19
2012 9 20
2012 9 21
2012 9 24
2012 9 25
2012 9 26
2012 9 27
2012 9 28
2012 10 2
2012 10 4
2012 10 5
2012 10 8
2012 10 9
2012 10 10
2012 10 11
2012 10 12
2012 10 15
2012 10 16
2012 10 17
2012 10 18
2012 10 19
2012 10 22
2012 10 23
2012 10 24
2012 10 25
2012 10 26
2012 10 29
2012 10 30
2012 10 31
2012 11 1
2012 11 2
2012 11 5
2012 11 6
2012 11 7
2012 11 8
2012 11 9
2012 11 12
2012 11 13
2012 11 14
2012 11 15
2012 11 16
2012 11 19
2012 11 20
2012 11 21
2012 11 22
2012 11 23
2012 11 26
2012 11 27
2012 11 28
2012 11 29
2012 11 30
2012 12 3
2012 12 4
2012 12 5
2012 12 6
2012 12 7
2012 12 10
2012 12 11
2012 12 12
2012 12 13
2012 12 14
2012 12 17
2012 12 18
2012 12 20
2012 12 21
2012 12 24
2012 12 26
2012 12 27
2012 12 28
2012 12 31
2013 1 2
2013 1 3
2013 1 4
2013 1 7
2013 1 8
2013 1 9
2013 1 10
2013 1 11
2013 1 14
2013 1 15
2013 1 16
2013 1 17
2013 1 18
2013 1 21
2013 1 22
2013 1 23
2013 1 24
2013 1 25
2013 1 28
2013 1 29
2013 1 30
2013 1 31
2013 2 1
2013 2 4
2013 2 5
2013 2 6
2013 2 7
2013 2 8
2013 2 12
2013 2 13
2013 2 14
2013 2 15
2013 2 18
2013 2 19
2013 2 20
2013 2 21
2013 2 22
2013 2 25
2013 2 26
2013 2 27
2013 2 28
2013 3 4
2013 3 5
2013 3 6
2013 3 7
2013 3 8
2013 3 11
2013 3 12
2013 3 13
2013 3 14
2013 3 15
2013 3 18
2013 3 19
2013 3 20
2013 3 21
2013 3 22
2013 3 25
2013 3 26
2013 3 27
2013 3 28
2013 3 29
2013 4 1
2013 4 2
2013 4 3
2013 4 4
2013 4 5
2013 4 8
2013 4 9
2013 4 10
2013 4 11
2013 4 12
2013 4 15
2013 4 16
2013 4 17
2013 4 18
2013 4 19
2013 4 22
2013 4 23
2013 4 24
2013 4 25
2013 4 26
2013 4 29
2013 4 30
2013 5 2
2013 5 3
2013 5 6
2013 5 7
2013 5 8
2013 5 9
2013 5 10
2013 5 13
2013 5 14
2013 5 15
2013 5 16
2013 5 20
2013 5 21
2013 5 22
2013 5 23
2013 5 24
2013 5 27
2013 5 28
2013 5 29
2013 5 30
2013 5 31
2013 6 3
2013 6 4
2013 6 5
2013 6 7
2013 6 10
2013 6 11
2013 6 12
2013 6 13
2013 6 14
2013 6 17
2013 6 18
2013 6 19
2013 6 20
2013 6 21
2013 6 24
2013 6 25
2013 6 26
2013 6 27
2013 6 28
2013 7 1
2013 7 2
2013 7 3
2013 7 4
2013 7 5
2013 7 8
2013 7 9
2013 7 10
2013 7 11
2013 7 12
2013 7 15
2013 7 16
2013 7 17
2013 7 18
2013 7 19
2013 7 22
2013 7 23
2013 7 24
2013 7 25
2013 7 26
2013 7 29
2013 7 30
2013 7 31
2013 8 1
2013 8 2
2013 8 5
2013 8 6
2013 8 7
2013 8 8
2013 8 9
2013 8 12
2013 8 13
2013 8 14
2013 8 16
2013 8 19
2013 8 20
2013 8 21
2013 8 22
2013 8 23
2013 8 26
2013 8 27
2013 8 28
2013 8 29
2013 8 30
2013 9 2
2013 9 3
2013 9 4
2013 9 5
2013 9 6
2013 9 9
2013 9 10
2013 9 11
2013 9 12
2013 9 13
2013 9 16
2013 9 17
2013 9 23
2013 9 24
2013 9 25
2013 9 26
2013 9 27
2013 9 30
2013 10 1
2013 10 2
2013 10 4
2013 10 7
2013 10 8
2013 10 10
2013 10 11
2013 10 14
2013 10 15
2013 10 16
2013 10 17
2013 10 18
2013 10 21
2013 10 22
2013 10 23
2013 10 24
2013 10 25
2013 10 28
2013 10 29
2013 10 30
2013 10 31
2013 11 1
2013 11 4
2013 11 5
2013 11 6
2013 11 7
2013 11 8
2013 11 11
2013 11 12
2013 11 13
2013 11 14
2013 11 15
2013 11 18
2013 11 19
2013 11 20
2013 11 21
2013 11 22
2013 11 25
2013 11 26
2013 11 27
2013 11 28
2013 11 29
2013 12 2
2013 12 3
2013 12 4
2013 12 5
2013 12 6
2013 12 9
2013 12 10
2013 12 11
2013 12 12
2013 12 13
2013 12 16
2013 12 17
2013 12 18
2013 12 19
2013 12 20
2013 12 23
2013 12 24
2013 12 26
2013 12 27
2013 12 30
2013 12 31
2014 1 2
2014 1 3
2014 1 6
2014 1 7
2014 1 8
2014 1 9
2014 1 10
2014 1 13
2014 1 14
2014 1 15
2014 1 16
2014 1 17
2014 1 20
2014 1 21
2014 1 22
2014 1 23
2014 1 24
2014 1 27
2014 1 28
2014 1 29
2014 2 3
2014 2 4
2014 2 5
2014 2 6
2014 2 7
2014 2 10
2014 2 11
2014 2 12
2014 2 13
2014 2 14
2014 2 17
2014 2 18
2014 2 19
2014 2 20
2014 2 21
2014 2 24
2014 2 25
2014 2 26
2014 2 27
2014 2 28
2014 3 3
2014 3 4
2014 3 5
2014 3 6
2014 3 7
2014 3 10
2014 3 11
2014 3 12
2014 3 14
2014 3 17
2014 3 18
2014 3 19
2014 3 20
2014 3 21
2014 3 24
2014 3 25
2014 3 26
2014 3 27
2014 3 28
2014 3 31
2014 4 1
2014 4 2
2014 4 3
2014 4 4
2014 4 7
2014 4 8
2014 4 9
2014 4 10
2014 4 11
2014 4 14
2014 4 15
2014 4 16
2014 4 17
2014 4 18
2014 4 21
2014 4 22
2014 4 23
2014 4 24
2014 4 25
2014 4 28
2014 4 29
2014 4 30
2014 5 2
2014 5 7
2014 5 8
2014 5 9
2014 5 12
2014 5 13
2014 5 14
2014 5 15
2014 5 16
2014 5 19
2014 5 20
2014 5 21
2014 5 22
2014 5 23
2014 5 26
2014 5 27
2014 5 28
2014 5 29
2014 5 30
2014 6 2
2014 6 3
2014 6 5
2014 6 9
2014 6 10
2014 6 11
2014 6 12
2014 6 13
2014 6 16
2014 6 17
2014 6 18
2014 6 19
2014 6 20
2014 6 23
2014 6 24
2014 6 25
2014 6 26
2014 6 27
2014 6 30
2014 7 1
2014 7 2
2014 7 3
2014 7 4
2014 7 7
2014 7 8
2014 7 9
2014 7 10
2014 7 11
2014 7 14
2014 7 15
2014 7 16
2014 7 17
2014 7 18
2014 7 21
2014 7 22
2014 7 23
2014 7 24
2014 7 25
2014 7 28
2014 7 29
2014 7 30
2014 7 31
2014 8 1
2014 8 4
2014 8 5
2014 8 6
2014 8 7
2014 8 8
2014 8 11
2014 8 12
2014 8 13
2014 8 14
2014 8 18
2014 8 19
2014 8 20
2014 8 21
2014 8 22
2014 8 25
2014 8 26
2014 8 27
2014 8 28
2014 8 29
2014 9 1
2014 9 2
2014 9 3
2014 9 4
2014 9 5
2014 9 11
2014 9 12
2014 9 15
2014 9 16
2014 9 17
2014 9 18
2014 9 19
2014 9 22
2014 9 23
2014 9 24
2014 9 25
2014 9 26
2014 9 29
2014 9 30
2014 10 1
2014 10 2
2014 10 6
2014 10 7
2014 10 8
2014 10 10
2014 10 13
2014 10 14
2014 10 15
2014 10 16
2014 10 17
2014 10 20
2014 10 21
2014 10 22
2014 10 23
2014 10 24
2014 10 27
2014 10 28
2014 10 29
2014 10 30
2014 10 31
2014 11 3
2014 11 4
2014 11 5
2014 11 6
2014 11 7
2014 11 10
2014 11 11
2014 11 12
2014 11 13
2014 11 14
2014 11 17
2014 11 18
2014 11 19
2014 11 20
2014 11 21
2014 11 24
2014 11 25
2014 11 26
2014 11 27
2014 11 28
2014 12 1
2014 12 2
2014 12 3
2014 12 4
2014 12 5
2014 12 8
2014 12 9
2014 12 10
2014 12 11
2014 12 12
2014 12 15
2014 12 16
2014 12 17
2014 12 18
2014 12 19
2014 12 22
2014 12 23
2014 12 24
2014 12 26
2014 12 29
2014 12 30
2014 12 31
2015 1 2
2015 1 5
2015 1 6
2015 1 7
2015 1 8
2015 1 9
2015 1 12
2015 1 13
2015 1 14
2015 1 15
2015 1 16
2015 1 19
2015 1 20
2015 1 21
2015 1 22
2015 1 23
2015 1 26
2015 1 27
2015 1 28
2015 1 29
2015 1 30
2015 2 2
2015 2 3
2015 2 4
2015 2 5
2015 2 6
2015 2 9
2015 2 10
2015 2 11
2015 2 12
2015 2 13
2015 2 16
2015 2 17
2015 2 23
2015 2 24
2015 2 25
2015 2 26
2015 2 27
2015 3 2
2015 3 3
2015 3 4
2015 3 5
2015 3 6
2015 3 9
2015 3 10
2015 3 11
2015 3 12
2015 3 13
2015 3 16
2015 3 17
2015 3 18
2015 3 19
2015 3 20
2015 3 23
2015 3 24
2015 3 25
2015 3 26
2015 3 27
2015 3 30
2015 3 31
2015 4 1
2015 4 2
2015 4 3
2015 4 6
2015 4 7
2015 4 8
2015 4 9
2015 4 10
2015 4 13
2015 4 14
2015 4 15
2015 4 16
2015 4 17
2015 4 20
2015 4 21
2015 4 22
2015 4 23
2015 4 24
2015 4 27
2015 4 28
2015 4 29
2015 4 30
2015 5 4
2015 5 6
2015 5 7
2015 5 8
2015 5 11
2015 5 12
2015 5 13
2015 5 14
2015 5 15
2015 5 18
2015 5 19
2015 5 20
2015 5 21
2015 5 22
2015 5 26
2015 5 27
2015 5 28
2015 5 29
2015 6 1
2015 6 2
2015 6 3
2015 6 4
2015 6 5
2015 6 8
2015 6 9
2015 6 10
2015 6 11
2015 6 12
2015 6 15
2015 6 16
2015 6 17
2015 6 18
2015 6 19
2015 6 22
2015 6 23
2015 6 24
2015 6 25
2015 6 26
2015 6 29
2015 6 30
2015 7 1
2015 7 2
2015 7 3
2015 7 6
2015 7 7
2015 7 8
2015 7 9
2015 7 10
2015 7 13
2015 7 14
2015 7 15
2015 7 16
2015 7 17
2015 7 20
2015 7 21
2015 7 22
2015 7 23
2015 7 24
2015 7 27
2015 7 28
2015 7 29
2015 7 30
2015 7 31
2015 8 3
2015 8 4
2015 8 5
2015 8 6
2015 8 7
2015 8 10
2015 8 11
2015 8 12
2015 8 13
2015 8 17
2015 8 18
2015 8 19
2015 8 20
2015 8 21
2015 8 24
2015 8 25
2015 8 26
2015 8 27
2015 8 28
2015 8 31
2015 9 1
2015 9 2
2015 9 3
2015 9 4
2015 9 7
2015 9 8
2015 9 9
2015 9 10
2015 9 11
2015 9 14
2015 9 15
2015 9 16
2015 9 17
2015 9 18
2015 9 21
2015 9 22
2015 9 23
2015 9 24
2015 9 25
2015 9 30
2015 10 1
2015 10 2
2015 10 5
2015 10 6
2015 10 7
2015 10 8
2015 10 12
2015 10 13
2015 10 14
2015 10 15
2015 10 16
2015 10 19
2015 10 20
2015 10 21
2015 10 22
2015 10 23
2015 10 26
2015 10 27
2015 10 28
2015 10 29
2015 10 30
2015 11 2
2015 11 3
2015 11 4
2015 11 5
2015 11 6
2015 11 9
2015 11 10
2015 11 11
2015 11 12
2015 11 13
2015 11 16
2015 11 17
2015 11 18
2015 11 19
2015 11 20
2015 11 23
2015 11 24
2015 11 25
2015 11 26
2015 11 27
2015 11 30
2015 12 1
2015 12 2
2015 12 3
2015 12 4
2015 12 7
2015 12 8
2015 12 9
2015 12 10
2015 12 11
2015 12 14
2015 12 15
2015 12 16
2015 12 17
2015 12 18
2015 12 21
2015 12 22
2015 12 23
2015 12 24
2015 12 28
2015 12 29
2015 12 30
2015 12 31
2016 1 4
2016 1 5
2016 1 6
2016 1 7
2016 1 8
2016 1 11
2016 1 12
2016 1 13
2016 1 14
2016 1 15
2016 1 18
2016 1 19
2016 1 20
2016 1 21
2016 1 22
2016 1 25
2016 1 26
2016 1 27
2016 1 28
2016 1 29
2016 2 1
2016 2 2
2016 2 3
2016 2 4
2016 2 5
2016 2 11
2016 2 12
2016 2 15
2016 2 16
2016 2 17
2016 2 18
2016 2 19
2016 2 22
2016 2 23
2016 2 24
2016 2 25
2016 2 26
2016 2 29
2016 3 2
2016 3 3
2016 3 4
2016 3 7
2016 3 8
2016 3 9
2016 3 10
2016 3 11
2016 3 14
2016 3 15
2016 3 16
2016 3 17
2016 3 18
2016 3 21
2016 3 22
2016 3 23
2016 3 24
2016 3 25
2016 3 28
2016 3 29
2016 3 30
2016 3 31
2016 4 1
2016 4 4
2016 4 5
2016 4 6
2016 4 7
2016 4 8
2016 4 11
2016 4 12
2016 4 14
2016 4 15
2016 4 18
2016 4 19
2016 4 20
2016 4 21
2016 4 22
2016 4 25
2016 4 26
2016 4 27
2016 4 28
2016 4 29
2016 5 2
2016 5 3
2016 5 9
2016 5 10
2016 5 11
2016 5 12
2016 5 13
2016 5 16
2016 5 17
2016 5 18
2016 5 19
2016 5 20
2016 5 23
2016 5 24
2016 5 25
2016 5 26
2016 5 27
2016 5 30
2016 5 31
2016 6 1
2016 6 2
2016 6 3
2016 6 7
2016 6 8
2016 6 9
2016 6 10
2016 6 13
2016 6 14
2016 6 15
2016 6 16
2016 6 17
2016 6 20
2016 6 21
2016 6 22
2016 6 23
2016 6 24
2016 6 27
2016 6 28
2016 6 29
2016 6 30
2016 7 1
2016 7 4
2016 7 5
2016 7 6
2016 7 7
2016 7 8
2016 7 11
2016 7 12
2016 7 13
2016 7 14
2016 7 15
2016 7 18
2016 7 19
2016 7 20
2016 7 21
2016 7 22
2016 7 25
2016 7 26
2016 7 27
2016 7 28
2016 7 29
2016 8 1
2016 8 2
2016 8 3
2016 8 4
2016 8 5
2016 8 8
2016 8 9
2016 8 10
2016 8 11
2016 8 12
2016 8 16
2016 8 17
2016 8 18
2016 8 19
2016 8 22
2016 8 23
2016 8 24
2016 8 25
2016 8 26
2016 8 29
2016 8 30
2016 8 31
2016 9 1
2016 9 2
2016 9 5
2016 9 6
2016 9 7
2016 9 8
2016 9 9
2016 9 12
2016 9 13
2016 9 19
2016 9 20
2016 9 21
2016 9 22
2016 9 23
2016 9 26
2016 9 27
2016 9 28
2016 9 29
2016 9 30
2016 10 4
2016 10 5
2016 10 6
2016 10 7
2016 10 10
2016 10 11
2016 10 12
2016 10 13
2016 10 14
2016 10 17
2016 10 18
2016 10 19
2016 10 20
2016 10 21
2016 10 24
2016 10 25
2016 10 26
2016 10 27
2016 10 28
2016 10 31
2016 11 1
2016 11 2
2016 11 3
2016 11 4
2016 11 7
2016 11 8
2016 11 9
2016 11 10
2016 11 11
2016 11 14
2016 11 15
2016 11 16
2016 11 17
2016 11 18
2016 11 21
2016 11 22
2016 11 23
2016 11 24
2016 11 25
2016 11 28
2016 11 29
2016 11 30
2016 12 1
2016 12 2
2016 12 5
2016 12 6
2016 12 7
2016 12 8
2016 12 9
2016 12 12
2016 12 13
2016 12 14
2016 12 15
2016 12 16
2016 12 19
2016 12 20
2016 12 21
2016 12 22
2016 12 23
2016 12 26
2016 12 27
2016 12 28
2016 12 29
2016 12 30
2017 1 2
2017 1 3
2017 1 4
2017 1 5
2017 1 6
2017 1 9
2017 1 10
2017 1 11
2017 1 12
2017 1 13
2017 1 16
2017 1 17
2017 1 18
2017 1 19
2017 1 20
2017 1 23
2017 1 24
2017 1 25
2017 1 26
2017 1 31
2017 2 1
2017 2 2
2017 2 3
2017 2 6
2017 2 7
2017 2 8
2017 2 9
2017 2 10
2017 2 13
2017 2 14
2017 2 15
2017 2 16
2017 2 17
2017 2 20
2017 2 21
2017 2 22
2017 2 23
2017 2 24
2017 2 27
2017 2 28
2017 3 2
2017 3 3
2017 3 6
2017 3 7
2017 3 8
2017 3 9
2017 3 10
2017 3 13
2017 3 14
2017 3 15
2017 3 16

2017 3 17
2017 3 20
2017 3 21
2017 3 22
2017 3 23
2017 3 24
2017 3 27
2017 3 28
2017 3 29
2017 3 30
2017 3 31
2017 4 3
2017 4 4
2017 4 5
2017 4 6
2017 4 7
2017 4 10
2017 4 11
2017 4 12
2017 4 13
2017 4 14
2017 4 17
2017 4 18
2017 4 19
2017 4 20
2017 4 21
2017 4 24
2017 4 25
2017 4 26
2017 4 27
2017 4 28
2017 5 2
2017 5 4
2017 5 8
2017 5 10
2017 5 11
2017 5 12
2017 5 15
2017 5 16
2017 5 17
2017 5 18
2017 5 19
2017 5 22
2017 5 23
2017 5 24
2017 5 25
2017 5 26
2017 5 29
2017 5 30
2017 5 31
2017 6 1
2017 6 2
2017 6 5
2017 6 7
2017 6 8
2017 6 9
2017 6 12
2017 6 13
2017 6 14
2017 6 15
2017 6 16
2017 6 19
2017 6 20
2017 6 21
2017 6 22
2017 6 23
2017 6 26
2017 6 27
2017 6 28
2017 6 29
2017 6 30
2017 7 3
2017 7 4
2017 7 5
2017 7 6
2017 7 7
2017 7 10
2017 7 11
2017 7 12
2017 7 13
2017 7 14
2017 7 17
2017 7 18
2017 7 19
2017 7 20
2017 7 21
2017 7 24
2017 7 25
2017 7 26
2017 7 27
2017 7 28
2017 7 31
2017 8 1
2017 8 2
2017 8 3
2017 8 4
2017 8 7
2017 8 8
2017 8 9
2017 8 10
2017 8 11
2017 8 14
2017 8 16
2017 8 17
2017 8 18
2017 8 21
2017 8 22
2017 8 23
2017 8 24
2017 8 25
2017 8 28
2017 8 29
2017 8 30
2017 8 31
2017 9 1
2017 9 4
2017 9 5
2017 9 6
2017 9 7
2017 9 8
2017 9 11
2017 9 12
2017 9 13
2017 9 14
2017 9 15
2017 9 18
2017 9 19
2017 9 20
2017 9 21
2017 9 22
2017 9 25
2017 9 26
2017 9 27
2017 9 28
2017 9 29
2017 10 10
2017 10 11
2017 10 12
2017 10 13
2017 10 16
2017 10 17
2017 10 18
2017 10 19
2017 10 20
2017 10 23
2017 10 24
2017 10 25
2017 10 26
2017 10 27
2017 10 30
2017 10 31
2017 11 1
2017 11 2
2017 11 3
2017 11 6
2017 11 7
2017 11 8
2017 11 9
2017 11 10
2017 11 13
2017 11 14
2017 11 15
2017 11 16
2017 11 17
2017 11 20
2017 11 21
2017 11 22
2017 11 23
2017 11 24
2017 11 27
2017 11 28
2017 11 29
2017 11 30
2017 12 1
2017 12 4
2017 12 5
2017 12 6
2017 12 7
2017 12 8
2017 12 11
2017 12 12
2017 12 13
2017 12 14
2017 12 15
2017 12 18
2017 12 19
2017 12 20
2017 12 21
2017 12 22
2017 12 26
2017 12 27
2017 12 28
2017 12 29